### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [dougg3/chumby8-linux-patches#1]
Hello!

I found this project from https://hackaday.com/2022/12/21/chumby-gets-new-kernel-soon/

Could you please add information about the license of this repository? If I understand correctly, the code is based on Linux Kernel, so the license should be GPL v2.

**Comment by dougg3** [comment]
Hi there! You are absolutely correct. I will add license info for these old patches. However, this repo is not actually where I've been doing any of my recent work -- I was a Git newbie at the time and this was just a place where I stored my patches. The kernel work I've actually been doing is here:

https://github.com/dougg3/silvermoon-linux

**Comment by dougg3** [comment]
License file has been added. Thanks for pointing that out!

**Comment by vazhnov** [comment]
@dougg3, thank you very much!

P.S.: I'm envy to your knowledge level of Linux, so you can port it to "new" devices. Amazing!
